## Sources for this Video

1. Take materials from the Ch-1 of below

/media/veracrypt2/ML/TENSORFLOW_Only/1_SELECTED-TF/State-of-the-Art-Deep-Learning-Models-in-TensorFlow-Google-Colab-Ecosystem-2021-USD-52


2. Daniel Burke - Udemy Zero to Mastery Introductory Vids



In [1]:
import tensorflow as tf
print(tf.__version__)

import warnings
warnings.filterwarnings('ignore')

2021-08-27 16:13:26.311542: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-27 16:13:26.311568: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "


2.6.0


# What are Tensors

Tensor are multi-dimensitonal arrays that are used in Tensorflow.

All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.

# Difference between Tensorflow tensor and numpy array

Tensors are more generalized vectors. Thus every tensor can be represented as a multidimensional array or vector, but not every vector can be represented as tensors.

Hence as numpy arrays can easily be replaced with tensorflow’s tensor , but the reverse is not true.

Another difference between a NumPy array and a tensor is that the tensors are backed by the accelerator memory like . So tensors can be used on GPUs and TPUs. 


### We use the following definition:

Rank: The number of dimensions that a vector has.

![Imgur](https://imgur.com/Q0dwaoF.png)

[Source](https://towardsdatascience.com/mastering-tensorflow-tensors-in-5-easy-steps-35f21998bb86)

Below, we will define different kinds of tensors and show their rank using tf.rank function.

---

## [tf.constant](https://www.tensorflow.org/api_docs/python/tf/constant)

Creates a constant tensor from a tensor-like object.

Lets quickly checkout their documentation



In [2]:
tensor = tf.constant(0)

print("Print constant tensor {} of rank {}".format(tensor, tf.rank(tensor)))

print("Show full tensor:", tensor)

Print constant tensor 0 of rank 0
Show full tensor: tf.Tensor(0, shape=(), dtype=int32)


2021-08-27 16:13:29.120816: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-08-27 16:13:29.121201: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-27 16:13:29.121288: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2021-08-27 16:13:29.121355: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2021-08-27 16:13:29.121411: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

In TensorFlow the differences between constants and variables are that when you declare some constant, its value can't be changed in the future (also the initialization should be with a value, not with operation).

Nevertheless, when you declare a Variable, you can change its value in the future with [tf.assign()](https://www.tensorflow.org/api_docs/python/tf/Variable#assign) method (and the initialization can be achieved with a value or operation).

In [3]:
# NOTE: We use .numpy() to transform tf.tensor to numpy

tensor = tf.constant([1,2,3])
# tensor = tf.constant([[1,2,3], [4,8,7]])
print("Tensor:", tensor)
# print("Rank:", tf.rank(tensor).numpy())
print(tf.rank(tensor).numpy())

Tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
1


*********** DONE UPTO HERE ***********

## Tensor Operations

In [4]:
tensor.ndim

1

In [5]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      
                      [[7, 8, 9],
                       [10, 11, 12]],
                      
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

## datatype of Tensors

By default, TensorFlow creates tensors with either an `int32` or `float32` datatype.

This is known as [32-bit precision](https://en.wikipedia.org/wiki/Precision_(computer_science) (the higher the number, the more precise the number, the more space it takes up on your computer).

In [6]:
tensor_float16  = tf.constant([[10., 7.],
                              [3., 2.]
                              ], dtype=tf.float16) # specify the datatype with 'dtype'
tensor_float16

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.]], dtype=float16)>

## Creating Tensors with `tf.Variable()`

I can also  create tensors using [`tf.Variable()`](https://www.tensorflow.org/api_docs/python/tf/Variable).

The difference between `tf.Variable()` and `tf.constant()` is tensors created with `tf.constant()` are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable()` are mutable (can be changed).

In [7]:
# Create the same tensor with tf.Variable() and tf.constant()
mutable_tensor = tf.Variable([4, 5])

immuable_tensor = tf.constant([6, 7])

mutable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [8]:
# immuable_tensor[0] = 12

In [9]:
mutable_tensor[0].assign(12)
mutable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12,  5], dtype=int32)>

# ************************

In [10]:
x = tf.constant([[1, 1],
                 [1, 1]])
y = tf.constant([[2, 4],
                 [6, 8]])

In [11]:
# Add two tensors
print(tf.add(x, y), "\n")

# Add two tensors
print(tf.matmul(x, y), "\n")

tf.Tensor(
[[3 5]
 [7 9]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 8 12]
 [ 8 12]], shape=(2, 2), dtype=int32) 



### Muti-dimentional Tensors

This part is not much different compared to what we learned so far. However, it would be nice to try extracting as much information as we can from a multi-dimentional tensor.

Let's use [tf.ones](https://www.tensorflow.org/api_docs/python/tf/ones) for our purpose here. It creates an all-one tensor.

In [12]:
# We set the shape of the tensor and the desired data type.
tensor = tf.ones(shape = [2, 3, 6], dtype = tf.float32)
print('Tensor:', tensor)

Tensor: tf.Tensor(
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]], shape=(2, 3, 6), dtype=float32)


## Creating Random Tensors

Random tensors are tensors of some abitrary size which contain random numbers.

Why we need them

This is what neural networks use to intialize their weights (patterns) that they're trying to learn in the data.

For example, the process of a neural network learning often involves taking a random n-dimensional array of numbers and refining them until they represent some kind of pattern (a compressed way to represent the original data).

In [13]:
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility

random_2 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 


random_3 = random_1.uniform(shape=(3, 2))
random_3


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7647915 , 0.03845465],
       [0.8506975 , 0.20781887],
       [0.711869  , 0.8843919 ]], dtype=float32)>

## What is seed in Tensorflow

The term "seed" is an abbreviation of the standard term "random seed".

TensorFlow operators that produce random results accept an optional seed parameter. If you pass the same number to two instances of the same operator, they will produce the same sequence of results. If you not pass a number to such an operator, it will produce different results on each execution.

This is not a tensorflow specific term, in fact almost any programming language have a seed for random generators, with a seed you make sure that you can reproduce your results when using random generators(using the same seed two times, would result in the same random number)

In [14]:
a = tf.random.shuffle([1,2,3,4,5,6], seed=567436).numpy()
b = tf.random.shuffle([1,2,3,4,5,6], seed=567436).numpy()
a == b

array([ True, False,  True, False,  True, False])

In [15]:
tf.random.set_seed(123456)
a = tf.random.shuffle([1,2,3,4,5,6], seed=567436).numpy()
tf.random.set_seed(123456)
b = tf.random.shuffle([1,2,3,4,5,6], seed=567436).numpy()
a == b

array([ True,  True,  True,  True,  True,  True])

## Important Note - the call to the global seed with tf.random.set_seed() - should be done before each operation.

https://www.tensorflow.org/api_docs/python/tf/random/set_seed

# The tf.data API

The tf.data API revolves around the concept of a dataset, which represents a sequence of data items. 

The tf.data API enables creation of flexible and efficient input pipelines by delivering
data for the next step of training before the current step has finished.


Let's create our first TensorFlow dataset now.

In [16]:
X = tf.range(5)
X

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

The dataset is a vector with five NumPy *int32* values ranging from 0 to 4.

We can easily display actual values from the TensorFlow tensor we just created:

In [17]:
X.numpy()

array([0, 1, 2, 3, 4], dtype=int32)

# Let's convert the dataset to a TensorFlow dataset with 'from_tensor_slices'

In [18]:
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

The **from_tensor_slices** functions takes a tensor and creates a **tf.data.Dataset** whose elements are all the slices of **X** (along the first dimension). 

So, **dataset** contains five items, namely, tensors 0 to 4. 

Notice that the shape is '()', which indicates that the elements are scalars.

# Iterate a tf.data.Dataset

We can simply iterate over the dataset items as so:

In [19]:
for item in dataset:
  print (item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


Depending on the data position and format, the tf.data.Dataset class offers many
static methods to use to create a dataset easily:

* Tensors in memory: tf.data.Dataset.from_tensors
* or tf.data.Dataset.from_tensor_slices. In this case, the tensors can be NumPy
* arrays or tf.Tensor objects.

From a Python generator: tf.data.Dataset.from_generator.

From a list of files that matches a pattern: tf.data.Dataset.list_files.

Also, there are two specializations of the `tf.data.Dataset` object created for working 
with two commonly used file formats:

* tf.data.TFRecordDataset - to work with the TFRecord files

* tf.data.TextLineDataset - to work with text files, reading them line by line


Let's say we want to define a dataset that produces an unlimited number of
vectors, each one with 100 elements, of random values. This is exactly what I will do a future video on a Generative Adversarial Networks Projcet.

So using `tf.data.Dataset.from_generator`, it is possible to do so in a few lines:

In [20]:

def noise():
    while True:
        yield tf.random.uniform((100,))


dataset = tf.data.Dataset.from_generator(noise, (tf.float32))


''' 

The only peculiarity of the from_generator method is the need to pass the type of
the parameters (tf.float32, in this case) as the second parameter; this is required
since to build a graph we need to know the type of the parameters in advance.

Using method chaining, it is possible to create new dataset objects, transforming
the one just built to get the data our machine learning model expects as input.

For example, if we want to 

- sum 10 to every component of the noise vector,
- shuffle the dataset content, and 
- create batches of 32 vectors each, we can do so

by calling just three methods chained together:


'''

buffer_size = 10
batch_size = 32

dataset = dataset.map(lambda x: x + 10).shuffle(buffer_size).batch(batch_size)

for idx, noise in enumerate(dataset):
    if idx == 2:
        break
    print(idx)
    print(noise.shape)


0
(32, 100)
1
(32, 100)


2021-08-27 19:54:17.544484: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


The `map` method is the most widely used method of the tf.data.Dataset object since
it allows us to apply a function to every element of the input dataset, producing a
new, transformed dataset.

The `shuffle` method is used in every training pipeline since this transformation
randomly shuffles the input dataset using a fixed-sized buffer; this means that
the shuffled data first fetches the buffer_size element from its input, then shuffles
them and produces the output.

The bat`c`h method gathers the batch_size elements from its input and creates a
batch as output. The only constraint of this transformation is that all elements of
the batch must have the same shape.
