In [2]:
import numpy as np


## The reshape() function is used to give a new shape to an array without changing its data.

`numpy.reshape(a, newshape, order='C')`

https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy-reshape

newshape	The new shape should be compatible with the original shape. If an integer, then the result will be a 1-D array of that length. One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.

The below example

![Imgur](https://imgur.com/fbjyxqd.png)


In [3]:
x = np.array([[2,3,4], [5,6,7]])
np.reshape(x, (3, 2))

array([[2, 3],
       [4, 5],
       [6, 7]])

In [7]:
a = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8]])
print('original shape of a ', a.shape)
b = np.reshape(a, -1)
b

original shape of a  (2, 4)


matrix([[1, 2, 3, 4, 5, 6, 7, 8]])

### numpy allow us to give one of new shape parameter as -1 (eg: (2,-1) or (-1,3) but not (-1, -1)). It simply means that it is an unknown dimension and we want numpy to figure it out. And numpy will figure this by looking at the 'length of the array and remaining dimensions' and making sure it satisfies the above mentioned criteria


for the below example the output explains the resultant vector to be a single row.(-1) indicates the number of rows to be 1.
if the 

    a = numpy.matrix([[1, 2, 3, 4], [5, 6, 7, 8]])
    b = numpy.reshape(a, -1)

output:

    matrix([[1, 2, 3, 4, 5, 6, 7, 8]])

 The "-1" stands for "unknown dimension" which can should be infered from another dimension.

In [5]:
a = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.reshape(a, (1, -1))
b

matrix([[1, 2, 3, 4, 5, 6, 7, 8]])

But 

```python
a = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.reshape(a, (-1, 1))
```

Gives a column vector. 

#### Trying to reshape with (-1, 1) . We have provided column as 1 but rows as unknown . So we get result new shape as (8, 1).again compatible with original shape(2,4)

#### The above is consistent with numpy advice/error message, to use reshape(-1,1) for a single feature; i.e. single column

Reshape your data using `array.reshape(-1, 1)` if your data has a single feature

In [6]:
a = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.reshape(a, (-1, 1))
b

matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])


And finally, if we try to provide both dimension as unknown i.e new shape as (-1,-1). It will throw an error

```python
a.reshape(-1, -1)
ValueError: can only specify one unknown dimension
```