In [6]:
import tensorflow as tf
print(tf.__version__)

import warnings
warnings.filterwarnings('ignore')

2.6.0


# What are Tensors

Tensor are multi-dimensitonal arrays that are used in Tensorflow.

All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.

# Difference between Tensorflow tensor and numpy array

Tensors are more generalized vectors. Thus every tensor can be represented as a multidimensional array or vector, but not every vector can be represented as tensors.

Hence as numpy arrays can easily be replaced with tensorflow’s tensor , but the reverse is not true.

Another difference between a NumPy array and a tensor is that the tensors are backed by the accelerator memory like . So tensors can be used on GPUs and TPUs. 


### We use the following definition:

Rank: The number of dimensions that a vector has.

![Imgur](https://imgur.com/Q0dwaoF.png)

[Source](https://towardsdatascience.com/mastering-tensorflow-tensors-in-5-easy-steps-35f21998bb86)

Below, we will define different kinds of tensors and show their rank using tf.rank function.

---

## [tf.constant](https://www.tensorflow.org/api_docs/python/tf/constant)

Creates a constant tensor from a tensor-like object.

Lets quickly checkout their documentation



In [7]:
tensor = tf.constant(0)

print("Print constant tensor {} of rank {}".format(tensor, tf.rank(tensor)))

print("Show full tensor:", tensor)

Print constant tensor 0 of rank 0
Show full tensor: tf.Tensor(0, shape=(), dtype=int32)


In TensorFlow the differences between constants and variables are that when you declare some constant, its value can't be changed in the future (also the initialization should be with a value, not with operation).

Nevertheless, when you declare a Variable, you can change its value in the future with [tf.assign()](https://www.tensorflow.org/api_docs/python/tf/Variable#assign) method (and the initialization can be achieved with a value or operation).

In [8]:
# NOTE: We use .numpy() to transform tf.tensor to numpy

tensor = tf.constant([1,2,3])
print("Tensor:", tensor)
print("Rank:", tf.rank(tensor).numpy())

Tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Rank: 1


## Tensor Operations

In [9]:
x = tf.constant([[1, 1],
                 [1, 1]])
y = tf.constant([[2, 4],
                 [6, 8]])

In [10]:
# Add two tensors
print(tf.add(x, y), "\n")

# Add two tensors
print(tf.matmul(x, y), "\n")

tf.Tensor(
[[3 5]
 [7 9]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 8 12]
 [ 8 12]], shape=(2, 2), dtype=int32) 



### Muti-dimentional Tensors

This part is not much different compared to what we learned so far. However, it would be nice to try extracting as much information as we can from a multi-dimentional tensor.

Let's use [tf.ones](https://www.tensorflow.org/api_docs/python/tf/ones) for our purpose here. It creates an all-one tensor.

In [11]:
# We set the shape of the tensor and the desired data type.
tensor = tf.ones(shape = [2, 3, 6], dtype = tf.float32)
print('Tensor:', tensor)

Tensor: tf.Tensor(
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]], shape=(2, 3, 6), dtype=float32)
