In [20]:
import tensorflow as tf
print(tf.__version__)

import warnings
warnings.filterwarnings('ignore')

2.6.0


In [21]:
tensor = tf.constant(5)
print(tensor)

tf.Tensor(5, shape=(), dtype=int32)


In [22]:
tensor = tf.constant([1, 2, 3])
print(tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [23]:
tensor = tf.constant([[1, 2, 3], [2,3,9]])
# print(tensor)
print(tf.rank(tensor).numpy())

2


In [24]:
print(tensor.ndim)

2


In [25]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      
                      [[7, 8, 9],
                       [10, 11, 12]],
                      
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [26]:
tensor_float16 = tf.constant([[10, 7], [14, 15]], dtype=tf.float16)
tensor_float16

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [14., 15.]], dtype=float16)>

In [27]:
mutable_tensor = tf.Variable([4, 5])

immuable_tensor = tf.constant([5, 6])

mutable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [28]:
# mutable_tensor[0] = 12
mutable_tensor[0].assign(12)
mutable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12,  5], dtype=int32)>

## Creating Random Tensors

In [29]:
random_gen = tf.random.Generator.from_seed(42)

random_normal = random_gen.normal(shape=(2, 3))
random_normal

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [30]:
random_uniform = random_gen.uniform(shape=(2, 3))
random_uniform

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.7647915 , 0.03845465, 0.8506975 ],
       [0.20781887, 0.711869  , 0.8843919 ]], dtype=float32)>

In [34]:
a = tf.random.shuffle([1,2,3,4,5], seed=2345).numpy()
b = tf.random.shuffle([1,2,3,4,5], seed=2345).numpy()
print(a == b)


[False  True False  True False]


In [35]:
tf.random.set_seed(2345)
a = tf.random.shuffle([1,2,3,4,5], seed=2345).numpy()
tf.random.set_seed(2345)
b = tf.random.shuffle([1,2,3,4,5], seed=2345).numpy()
print(a == b)

[ True  True  True  True  True]


# The tf.data API

In [46]:
X = tf.range(5)
X

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [47]:
X.numpy()

array([0, 1, 2, 3, 4], dtype=int32)

In [52]:
dataset = tf.data.Dataset.from_tensor_slices(X)
print(dataset)

<TensorSliceDataset shapes: (), types: tf.int32>


In [54]:
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
